[package]
name = "iter-matcher"
version = "0.1.0"
authors = ["Daniel Parks <oss-iter-matcher@demonhorse.org>"]
description = ""
homepage = "https://github.com/danielparks/iter-matcher"
repository = "https://github.com/danielparks/iter-matcher"
documentation = "https://github.com/danielparks/iter-matcher"
readme = "README.md"
keywords = []
categories = [] # https://crates.io/category_slugs
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]

[dev-dependencies]
anyhow = "1.0.68"
assert2 = "0.3.7"
clap = { version = "4.1.1", features = ["derive"] }
serde_json = "1.0.91"
temp-dir = "0.1.11"
