[workspace]
members = [".", "iter_matcher_tests"]
default-members = [".", "iter_matcher_tests"]

[workspace.package]
version = "0.1.0"
authors = ["Daniel Parks <oss-iter-matcher@demonhorse.org>"]
description = "Generate sequence matchers for iterators (experimental)"
homepage = "https://github.com/danielparks/iter-matcher"
repository = "https://github.com/danielparks/iter-matcher"
readme = "README.md"
keywords = []
categories = [] # https://crates.io/category_slugs
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.60"

[patch.crates-io]
iter_matcher = { path = "." }

[package]
name = "iter_matcher"
authors.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

[dev-dependencies]
bstr = { version = "1.1.0", default-features = false, features = ["std"] }
pretty_assertions = "1.3.0"
temp-dir = "0.1.11"
